package configcli

import (
	"fmt"
	"os"
	"sort"

	"github.com/sei-protocol/sei-chain/config/registry"
	"github.com/sei-protocol/sei-chain/config/seitoml"
	"github.com/sei-protocol/sei-chain/sei-cosmos/version"
)

// MonikerKey is the node's name, and the one generated value this binary will not invent.
const MonikerKey = "moniker"

// Generate renders the complete configuration for one node.
//
// This writes every declared key at the baseline for that mode, so the file holds the whole picture
// of what the node runs the moment it is generated.
//
// A written key is a commitment this binary never rewrites, and that applies to every key here. So a
// generated node does not follow a baseline a later release changes: it keeps the value the file
// records, and regenerating moves it forward. The preamble says so in the file, because an operator
// reading it otherwise cannot tell a value they chose from one generate filled in.
//
// The moniker is required rather than defaulted. Its baseline is the host name of whatever machine
// asked, so a file generated anywhere but the node it describes would carry another machine's identity,
// and a file copied to twenty nodes would give all twenty the same name. Taking it as an argument is
// what makes the file describe one node, which is what every value in it assumes.
func Generate(mode registry.Mode, moniker string) (*seitoml.File, error) {
	if err := knownMode(mode); err != nil {
		return nil, err
	}
	if moniker == "" {
		return nil, fmt.Errorf("generate needs a moniker: it names the node this file is for, and its " +
			"default is the host name of whichever machine runs this command, so leaving it out writes " +
			"one node's identity into another node's configuration")
	}
	resolved, err := registry.Resolve(mode)
	if err != nil {
		return nil, fmt.Errorf("resolve the baselines for mode %q: %w", mode, err)
	}
	if len(resolved.Keys) == 0 {
		return nil, fmt.Errorf("no section has registered a key, so generate would write an empty " +
			"file that reads as a node with nothing configured")
	}

	file, err := seitoml.New(string(mode), version.Version)
	if err != nil {
		return nil, err
	}
	file.SetPreamble(preamble(mode))

	// Sorted, so two runs of the same binary produce the same bytes and a diff between two nodes
	// compares configuration rather than map iteration order.
	for _, key := range sortedKeys(resolved) {
		value := resolved.Keys[key].Value
		if key == MonikerKey {
			value = moniker
		}
		if err := file.Set(key, value); err != nil {
			return nil, fmt.Errorf("write %s: %w", key, err)
		}
	}
	return file, nil
}

// HostDerivedElsewhere names the keys a file would carry from this machine rather than from the node it
// describes, and is empty when the two are the same machine.
//
// The moniker is taken as an argument, so it is right wherever this runs. The rest of the host-derived
// keys are not: they scale with the processor count of whichever machine resolved them. Generating on
// the node makes them right, and generating for a node elsewhere makes them this machine's.
//
// The moniker is what tells the two apart. It is the operator's statement of which node the file is for,
// so a moniker that is not this host's name is the one moment this can say the values came from
// somewhere else.
func HostDerivedElsewhere(moniker string) []string {
	host, err := os.Hostname()
	if err != nil || host == moniker {
		return nil
	}
	var elsewhere []string
	for _, key := range registry.HostDerivedKeys() {
		if key != MonikerKey {
			elsewhere = append(elsewhere, key)
		}
	}
	return elsewhere
}

// preamble is what the generated file says about itself.
//
// The mode also sits in the file as node_mode, which is what a check reads. This repeats it in prose
// for the operator, because every value below resolves for that mode alone and a file generated for
// one mode running on a node started in another is a configuration nobody intended.
func preamble(mode registry.Mode) []string {
	return []string{
		fmt.Sprintf(" Generated by seid config generate for a node running in %q mode.", mode),
		"",
		" Every key below is a written value, which this binary treats as your decision and",
		" never rewrites. That includes the ones generate filled in from its own defaults, so",
		" this node keeps these values across an upgrade even where a later release ships a",
		" different default. Run seid config generate again to move to the current defaults.",
		"",
		" The values here were chosen for the mode named above. Running the node in another",
		" mode does not re-resolve them.",
	}
}

// sortedKeys returns the resolved keys in a stable order.
func sortedKeys(resolved registry.Resolved) []string {
	keys := make([]string, 0, len(resolved.Keys))
	for k := range resolved.Keys {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// knownMode refuses a mode no section can produce a baseline for.
//
// Resolve would otherwise be asked for a mode the registry does not know, and a section's baseline
// function is free to answer for it with whatever its default branch returns. That would write a
// complete, plausible file for a mode no node runs.
func knownMode(mode registry.Mode) error {
	for _, m := range registry.Modes() {
		if m == mode {
			return nil
		}
	}
	return fmt.Errorf("%q is not a node mode; the modes are %v", mode, registry.Modes())
}
